# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'agregar_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Agregar_cliente(object):
    def setupUi(self, Agregar_cliente):
        Agregar_cliente.setObjectName("Agregar_cliente")
        Agregar_cliente.resize(325, 580)
        Agregar_cliente.setMinimumSize(QtCore.QSize(325, 580))
        Agregar_cliente.setMaximumSize(QtCore.QSize(325, 580))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Agregar_cliente.setWindowIcon(icon)
        Agregar_cliente.setStyleSheet("")
        self.widget = QtWidgets.QWidget(Agregar_cliente)
        self.widget.setGeometry(QtCore.QRect(-5, -2, 331, 591))
        self.widget.setStyleSheet("QWidget#widget {\n"
"    background-image: url(:/imagenes/gimnasio_agregar.jpg);\n"
"}")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 307, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.lay_ver_principal_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.lay_ver_principal_2.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal_2.setObjectName("lay_ver_principal_2")
        self.lbl_agregar_cliente_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_agregar_cliente_2.setStyleSheet("background-color: rgb(97, 97, 0);\n"
"border-radius:5px;\n"
"padding-right:30px;\n"
"padding-left:30px;\n"
"font: 30pt \"Gill Sans MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.lbl_agregar_cliente_2.setObjectName("lbl_agregar_cliente_2")
        self.lay_ver_principal_2.addWidget(self.lbl_agregar_cliente_2, 0, QtCore.Qt.AlignHCenter)
        self.lay_frm_datos_2 = QtWidgets.QFormLayout()
        self.lay_frm_datos_2.setHorizontalSpacing(15)
        self.lay_frm_datos_2.setVerticalSpacing(2)
        self.lay_frm_datos_2.setObjectName("lay_frm_datos_2")
        self.lbl_nombre_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_nombre_2.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_nombre_2.setObjectName("lbl_nombre_2")
        self.lay_frm_datos_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre_2)
        self.txt_nombre_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_nombre_2.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_nombre_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_nombre_2.setObjectName("txt_nombre_2")
        self.lay_frm_datos_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre_2)
        self.lbl_cedula_ti_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_cedula_ti_2.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_cedula_ti_2.setObjectName("lbl_cedula_ti_2")
        self.lay_frm_datos_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_cedula_ti_2)
        self.txt_cedula_ti_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_cedula_ti_2.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_cedula_ti_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_cedula_ti_2.setObjectName("txt_cedula_ti_2")
        self.lay_frm_datos_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_cedula_ti_2)
        self.lbl_objetivo_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_objetivo_2.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_objetivo_2.setObjectName("lbl_objetivo_2")
        self.lay_frm_datos_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_objetivo_2)
        self.lay_ver_objetivo_2 = QtWidgets.QVBoxLayout()
        self.lay_ver_objetivo_2.setSpacing(0)
        self.lay_ver_objetivo_2.setObjectName("lay_ver_objetivo_2")
        self.rdb_perder_peso_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdb_perder_peso_2.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.rdb_perder_peso_2.setObjectName("rdb_perder_peso_2")
        self.btn_group_objetivo = QtWidgets.QButtonGroup(Agregar_cliente)
        self.btn_group_objetivo.setObjectName("btn_group_objetivo")
        self.btn_group_objetivo.addButton(self.rdb_perder_peso_2)
        self.lay_ver_objetivo_2.addWidget(self.rdb_perder_peso_2)
        self.rdb_volumen_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdb_volumen_2.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.rdb_volumen_2.setObjectName("rdb_volumen_2")
        self.btn_group_objetivo.addButton(self.rdb_volumen_2)
        self.lay_ver_objetivo_2.addWidget(self.rdb_volumen_2)
        self.rdb_tonificar_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdb_tonificar_2.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.rdb_tonificar_2.setObjectName("rdb_tonificar_2")
        self.btn_group_objetivo.addButton(self.rdb_tonificar_2)
        self.lay_ver_objetivo_2.addWidget(self.rdb_tonificar_2)
        self.txt_otro_objetivo = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_otro_objetivo.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_otro_objetivo.setObjectName("txt_otro_objetivo")
        self.lay_ver_objetivo_2.addWidget(self.txt_otro_objetivo)
        self.lay_frm_datos_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.lay_ver_objetivo_2)
        self.lbl_patologias_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_patologias_2.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_patologias_2.setObjectName("lbl_patologias_2")
        self.lay_frm_datos_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_patologias_2)
        self.txt_patologias_2 = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.txt_patologias_2.setMinimumSize(QtCore.QSize(217, 83))
        self.txt_patologias_2.setMaximumSize(QtCore.QSize(217, 83))
        self.txt_patologias_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius:15px;\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_patologias_2.setObjectName("txt_patologias_2")
        self.lay_frm_datos_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_patologias_2)
        self.lbl_inscripcion_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_inscripcion_2.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_inscripcion_2.setObjectName("lbl_inscripcion_2")
        self.lay_frm_datos_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_inscripcion_2)
        self.lay_hor_inscripcion_2 = QtWidgets.QHBoxLayout()
        self.lay_hor_inscripcion_2.setObjectName("lay_hor_inscripcion_2")
        self.rdb_dia_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdb_dia_2.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.rdb_dia_2.setObjectName("rdb_dia_2")
        self.btn_group_inscripcion = QtWidgets.QButtonGroup(Agregar_cliente)
        self.btn_group_inscripcion.setObjectName("btn_group_inscripcion")
        self.btn_group_inscripcion.addButton(self.rdb_dia_2)
        self.lay_hor_inscripcion_2.addWidget(self.rdb_dia_2)
        self.rdb_mes_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdb_mes_2.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.rdb_mes_2.setObjectName("rdb_mes_2")
        self.btn_group_inscripcion.addButton(self.rdb_mes_2)
        self.lay_hor_inscripcion_2.addWidget(self.rdb_mes_2)
        self.rdb_anual_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdb_anual_2.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"color: rgb(255, 255, 255);\n"
"} ")
        self.rdb_anual_2.setObjectName("rdb_anual_2")
        self.btn_group_inscripcion.addButton(self.rdb_anual_2)
        self.lay_hor_inscripcion_2.addWidget(self.rdb_anual_2)
        self.lay_frm_datos_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.lay_hor_inscripcion_2)
        self.lbl_foto_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_foto_2.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_foto_2.setObjectName("lbl_foto_2")
        self.lay_frm_datos_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_foto_2)
        self.lbl_foto_cliente_2 = QtWidgets.QLabel(self.layoutWidget)
        self.lbl_foto_cliente_2.setMinimumSize(QtCore.QSize(217, 178))
        self.lbl_foto_cliente_2.setMaximumSize(QtCore.QSize(217, 178))
        self.lbl_foto_cliente_2.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius:20px;\n"
"padding:10px 20px 10px 20px;")
        self.lbl_foto_cliente_2.setText("")
        self.lbl_foto_cliente_2.setPixmap(QtGui.QPixmap(":/imagenes/agregar.png"))
        self.lbl_foto_cliente_2.setScaledContents(True)
        self.lbl_foto_cliente_2.setObjectName("lbl_foto_cliente_2")
        self.lay_frm_datos_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_foto_cliente_2)
        self.lay_ver_principal_2.addLayout(self.lay_frm_datos_2)
        self.btn_agregar_cliente = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_agregar_cliente.setStyleSheet("QPushButton#btn_agregar_cliente {\n"
"    background-color: rgba(255, 255, 0, 166);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_agregar_cliente:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_agregar_cliente:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_agregar_cliente.setObjectName("btn_agregar_cliente")
        self.lay_ver_principal_2.addWidget(self.btn_agregar_cliente)

        self.retranslateUi(Agregar_cliente)
        QtCore.QMetaObject.connectSlotsByName(Agregar_cliente)

    def retranslateUi(self, Agregar_cliente):
        _translate = QtCore.QCoreApplication.translate
        Agregar_cliente.setWindowTitle(_translate("Agregar_cliente", "Agregar cliente"))
        self.lbl_agregar_cliente_2.setText(_translate("Agregar_cliente", "Agregar cliente"))
        self.lbl_nombre_2.setText(_translate("Agregar_cliente", "Nombre:"))
        self.lbl_cedula_ti_2.setText(_translate("Agregar_cliente", "Cedula/T.I: "))
        self.lbl_objetivo_2.setText(_translate("Agregar_cliente", "objetivo:"))
        self.rdb_perder_peso_2.setText(_translate("Agregar_cliente", "Perder peso"))
        self.rdb_volumen_2.setText(_translate("Agregar_cliente", "Aumento de masa muscular"))
        self.rdb_tonificar_2.setText(_translate("Agregar_cliente", "Tonificar"))
        self.txt_otro_objetivo.setPlaceholderText(_translate("Agregar_cliente", "Otro..."))
        self.lbl_patologias_2.setText(_translate("Agregar_cliente", "Patologias:"))
        self.txt_patologias_2.setPlaceholderText(_translate("Agregar_cliente", "Inserte patologias separadar por una coma \",\""))
        self.lbl_inscripcion_2.setText(_translate("Agregar_cliente", "Inscripción:"))
        self.rdb_dia_2.setText(_translate("Agregar_cliente", "DIA"))
        self.rdb_mes_2.setText(_translate("Agregar_cliente", "MES"))
        self.rdb_anual_2.setText(_translate("Agregar_cliente", "AÑO"))
        self.lbl_foto_2.setText(_translate("Agregar_cliente", "Foto:"))
        self.btn_agregar_cliente.setText(_translate("Agregar_cliente", "Agregar"))
from gimnasio.images import imagenes_rc
