# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buscar_informacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Buscar_informacion_cliente(object):
    def setupUi(self, Buscar_informacion_cliente):
        Buscar_informacion_cliente.setObjectName("Buscar_informacion_cliente")
        Buscar_informacion_cliente.resize(330, 600)
        Buscar_informacion_cliente.setMinimumSize(QtCore.QSize(330, 600))
        Buscar_informacion_cliente.setMaximumSize(QtCore.QSize(330, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Buscar_informacion_cliente.setWindowIcon(icon)
        self.wdg_principal = QtWidgets.QWidget(Buscar_informacion_cliente)
        self.wdg_principal.setGeometry(QtCore.QRect(-1, -1, 341, 601))
        self.wdg_principal.setStyleSheet("QWidget #wdg_principal {\n"
"background-image: url(:/imagenes/gimnasio_buscar_informacion.jpg);\n"
"background-position: center;\n"
"}")
        self.wdg_principal.setObjectName("wdg_principal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wdg_principal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 321, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_buscar_informacion = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_buscar_informacion.setStyleSheet("background-color:rgba(241, 101, 103, 166);\n"
"border-radius:5px;\n"
"padding-right:30px;\n"
"padding-left:30px;\n"
"font: 30pt \"Gill Sans MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.lbl_buscar_informacion.setObjectName("lbl_buscar_informacion")
        self.lay_ver_principal.addWidget(self.lbl_buscar_informacion, 0, QtCore.Qt.AlignHCenter)
        self.lay_frm_principal = QtWidgets.QFormLayout()
        self.lay_frm_principal.setHorizontalSpacing(15)
        self.lay_frm_principal.setObjectName("lay_frm_principal")
        self.lbl_cedula_ti = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_cedula_ti.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_cedula_ti.setObjectName("lbl_cedula_ti")
        self.lay_frm_principal.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_cedula_ti)
        self.txt_cedula_TI = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_cedula_TI.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_cedula_TI.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_cedula_TI.setObjectName("txt_cedula_TI")
        self.lay_frm_principal.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_cedula_TI)
        self.btn_buscar_cliente = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_buscar_cliente.setStyleSheet("QPushButton#btn_buscar_cliente {\n"
"    background-color: rgba(255, 87, 90, 170);\n"
"    border-radius: 5px;\n"
"    margin-right:7px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_buscar_cliente:hover {\n"
"    background-color:rgba(255, 147, 149, 175);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_buscar_cliente:pressed {\n"
"    background-color:rgba(195, 50, 53, 200);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_buscar_cliente.setObjectName("btn_buscar_cliente")
        self.lay_frm_principal.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_buscar_cliente)
        self.lbl_nombre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_nombre.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lay_frm_principal.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_nombre.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_nombre.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_nombre.setReadOnly(True)
        self.txt_nombre.setObjectName("txt_nombre")
        self.lay_frm_principal.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        self.lbl_objetivo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_objetivo.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_objetivo.setObjectName("lbl_objetivo")
        self.lay_frm_principal.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_objetivo)
        self.txt_objetivo = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_objetivo.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_objetivo.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_objetivo.setReadOnly(True)
        self.txt_objetivo.setObjectName("txt_objetivo")
        self.lay_frm_principal.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_objetivo)
        self.lbl_patologias = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_patologias.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_patologias.setObjectName("lbl_patologias")
        self.lay_frm_principal.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_patologias)
        self.txt_patologias = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.txt_patologias.setMinimumSize(QtCore.QSize(217, 83))
        self.txt_patologias.setMaximumSize(QtCore.QSize(217, 83))
        self.txt_patologias.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius:15px;\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_patologias.setReadOnly(True)
        self.txt_patologias.setObjectName("txt_patologias")
        self.lay_frm_principal.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_patologias)
        self.lbl_inscripcion = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_inscripcion.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_inscripcion.setObjectName("lbl_inscripcion")
        self.lay_frm_principal.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_inscripcion)
        self.txt_inscripcion = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_inscripcion.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_inscripcion.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_inscripcion.setReadOnly(True)
        self.txt_inscripcion.setObjectName("txt_inscripcion")
        self.lay_frm_principal.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_inscripcion)
        self.lbl_Foto_cliente = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_Foto_cliente.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_Foto_cliente.setObjectName("lbl_Foto_cliente")
        self.lay_frm_principal.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_Foto_cliente)
        self.lbl_foto = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_foto.setMinimumSize(QtCore.QSize(217, 178))
        self.lbl_foto.setMaximumSize(QtCore.QSize(217, 178))
        self.lbl_foto.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius:20px;\n"
"padding:10px 20px 10px 20px;")
        self.lbl_foto.setText("")
        self.lbl_foto.setPixmap(QtGui.QPixmap(":/imagenes/persona.png"))
        self.lbl_foto.setScaledContents(True)
        self.lbl_foto.setObjectName("lbl_foto")
        self.lay_frm_principal.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lbl_foto)
        self.lbl_fecha_final = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_fecha_final.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_fecha_final.setObjectName("lbl_fecha_final")
        self.lay_frm_principal.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_fecha_final)
        self.dat_fecha_final = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dat_fecha_final.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"qproperty-alignment: AlignCenter;")
        self.dat_fecha_final.setReadOnly(True)
        self.dat_fecha_final.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dat_fecha_final.setObjectName("dat_fecha_final")
        self.lay_frm_principal.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dat_fecha_final)
        self.lbl_permiso = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_permiso.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_permiso.setObjectName("lbl_permiso")
        self.lay_frm_principal.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_permiso)
        self.chkentrada_gimnasio = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chkentrada_gimnasio.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.chkentrada_gimnasio.setObjectName("chkentrada_gimnasio")
        self.lay_frm_principal.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.chkentrada_gimnasio)
        self.lay_ver_principal.addLayout(self.lay_frm_principal)

        self.retranslateUi(Buscar_informacion_cliente)
        QtCore.QMetaObject.connectSlotsByName(Buscar_informacion_cliente)

    def retranslateUi(self, Buscar_informacion_cliente):
        _translate = QtCore.QCoreApplication.translate
        Buscar_informacion_cliente.setWindowTitle(_translate("Buscar_informacion_cliente", "Buscar información de un cliente"))
        self.lbl_buscar_informacion.setText(_translate("Buscar_informacion_cliente", "Buscar información"))
        self.lbl_cedula_ti.setText(_translate("Buscar_informacion_cliente", "Cedula/T.I: "))
        self.txt_cedula_TI.setPlaceholderText(_translate("Buscar_informacion_cliente", "Inserte aquí el No de Id/Cedula."))
        self.btn_buscar_cliente.setText(_translate("Buscar_informacion_cliente", "Buscar"))
        self.lbl_nombre.setText(_translate("Buscar_informacion_cliente", "Nombre:"))
        self.txt_nombre.setPlaceholderText(_translate("Buscar_informacion_cliente", "Aquí se mostrará el nombre"))
        self.lbl_objetivo.setText(_translate("Buscar_informacion_cliente", "objetivo:"))
        self.txt_objetivo.setPlaceholderText(_translate("Buscar_informacion_cliente", "Aquí se mostrará el objetivo"))
        self.lbl_patologias.setText(_translate("Buscar_informacion_cliente", "Patologias:"))
        self.txt_patologias.setPlaceholderText(_translate("Buscar_informacion_cliente", "Aquí se mostrarán las patologias"))
        self.lbl_inscripcion.setText(_translate("Buscar_informacion_cliente", "Inscripción:"))
        self.txt_inscripcion.setPlaceholderText(_translate("Buscar_informacion_cliente", "Aquí se mostrará el tipo de inscripción"))
        self.lbl_Foto_cliente.setText(_translate("Buscar_informacion_cliente", "Foto:"))
        self.lbl_fecha_final.setText(_translate("Buscar_informacion_cliente", "Fecha final:"))
        self.lbl_permiso.setText(_translate("Buscar_informacion_cliente", "Permiso:"))
        self.chkentrada_gimnasio.setText(_translate("Buscar_informacion_cliente", "Entrada al gimnasio"))
        self.chkentrada_gimnasio.setCheckable(False)
from gimnasio.images import imagenes_rc
