# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambiar_objetivo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ingresar_objetivo(object):
    def setupUi(self, Ingresar_objetivo):
        Ingresar_objetivo.setObjectName("Ingresar_objetivo")
        Ingresar_objetivo.resize(400, 137)
        Ingresar_objetivo.setMinimumSize(QtCore.QSize(400, 137))
        Ingresar_objetivo.setMaximumSize(QtCore.QSize(400, 137))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/lapiz_editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ingresar_objetivo.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Ingresar_objetivo)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_ingrese_nuevo_objetivo = QtWidgets.QLabel(Ingresar_objetivo)
        self.lbl_ingrese_nuevo_objetivo.setStyleSheet("font: 11pt \"Gill Sans MT\";")
        self.lbl_ingrese_nuevo_objetivo.setObjectName("lbl_ingrese_nuevo_objetivo")
        self.lay_ver_principal.addWidget(self.lbl_ingrese_nuevo_objetivo)
        self.lay_hor_objetivos = QtWidgets.QHBoxLayout()
        self.lay_hor_objetivos.setObjectName("lay_hor_objetivos")
        self.rdb_perder_peso = QtWidgets.QRadioButton(Ingresar_objetivo)
        self.rdb_perder_peso.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"} ")
        self.rdb_perder_peso.setObjectName("rdb_perder_peso")
        self.btn_group_objetivo = QtWidgets.QButtonGroup(Ingresar_objetivo)
        self.btn_group_objetivo.setObjectName("btn_group_objetivo")
        self.btn_group_objetivo.addButton(self.rdb_perder_peso)
        self.lay_hor_objetivos.addWidget(self.rdb_perder_peso)
        self.rdb_aumento_masa_muscular = QtWidgets.QRadioButton(Ingresar_objetivo)
        self.rdb_aumento_masa_muscular.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"} ")
        self.rdb_aumento_masa_muscular.setObjectName("rdb_aumento_masa_muscular")
        self.btn_group_objetivo.addButton(self.rdb_aumento_masa_muscular)
        self.lay_hor_objetivos.addWidget(self.rdb_aumento_masa_muscular)
        self.rdb_tonificar = QtWidgets.QRadioButton(Ingresar_objetivo)
        self.rdb_tonificar.setStyleSheet("QRadioButton {\n"
"  background-color: transparent;\n"
"  padding: 4px;\n"
"  color: #333333;\n"
"font: 9pt \"Gill Sans MT\";\n"
"}\n"
"QRadioButton::indicator {\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QRadioButton:indicator:checked:hover{\n"
"  background-color: rgb(34, 34, 255);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"  border: 1px solid #999999;\n"
"  background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover:unchecked {\n"
"  border: 1px solid rgb(32, 54, 255);\n"
"  background-color: #FFFFFF;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"  border: 1px solid rgb(0, 0, 0);\n"
"  background-color: rgb(139, 49, 184);\n"
"} ")
        self.rdb_tonificar.setObjectName("rdb_tonificar")
        self.btn_group_objetivo.addButton(self.rdb_tonificar)
        self.lay_hor_objetivos.addWidget(self.rdb_tonificar)
        self.lay_ver_principal.addLayout(self.lay_hor_objetivos)
        self.txt_otro_objetivo = QtWidgets.QLineEdit(Ingresar_objetivo)
        self.txt_otro_objetivo.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";")
        self.txt_otro_objetivo.setObjectName("txt_otro_objetivo")
        self.lay_ver_principal.addWidget(self.txt_otro_objetivo)
        self.btn_agregar = QtWidgets.QPushButton(Ingresar_objetivo)
        self.btn_agregar.setObjectName("btn_agregar")
        self.lay_ver_principal.addWidget(self.btn_agregar)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)

        self.retranslateUi(Ingresar_objetivo)
        QtCore.QMetaObject.connectSlotsByName(Ingresar_objetivo)

    def retranslateUi(self, Ingresar_objetivo):
        _translate = QtCore.QCoreApplication.translate
        Ingresar_objetivo.setWindowTitle(_translate("Ingresar_objetivo", "Nuevo Objetivo"))
        self.lbl_ingrese_nuevo_objetivo.setText(_translate("Ingresar_objetivo", "Ingrese el nuevo objetivo:"))
        self.rdb_perder_peso.setText(_translate("Ingresar_objetivo", "Perder peso"))
        self.rdb_aumento_masa_muscular.setText(_translate("Ingresar_objetivo", "Aumento de masa muscular"))
        self.rdb_tonificar.setText(_translate("Ingresar_objetivo", "Tonificar"))
        self.txt_otro_objetivo.setPlaceholderText(_translate("Ingresar_objetivo", "Otro..."))
        self.btn_agregar.setText(_translate("Ingresar_objetivo", "Agregar"))
