# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambiar_info_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cambiar_info_cliente(object):
    def setupUi(self, Cambiar_info_cliente):
        Cambiar_info_cliente.setObjectName("Cambiar_info_cliente")
        Cambiar_info_cliente.resize(493, 330)
        Cambiar_info_cliente.setMinimumSize(QtCore.QSize(493, 330))
        Cambiar_info_cliente.setMaximumSize(QtCore.QSize(493, 330))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/lapiz_editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Cambiar_info_cliente.setWindowIcon(icon)
        self.wdg_principal = QtWidgets.QWidget(Cambiar_info_cliente)
        self.wdg_principal.setGeometry(QtCore.QRect(-1, -1, 501, 331))
        self.wdg_principal.setStyleSheet("QWidget #wdg_principal {\n"
"    \n"
"    background-image: url(:/imagenes/gimnasio_cambiar_info.jpg);\n"
"    background-position: center;\n"
"}")
        self.wdg_principal.setObjectName("wdg_principal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wdg_principal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 474, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_ActualizarInfo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_ActualizarInfo.setStyleSheet("\n"
"background-color:rgba(206, 202, 59,210);\n"
"border: 4px solid rgba(118, 118, 0, 166);\n"
"border-radius:5px;\n"
"padding-right:30px;\n"
"padding-left:30px;\n"
"font: 30pt \"Gill Sans MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.lbl_ActualizarInfo.setObjectName("lbl_ActualizarInfo")
        self.lay_ver_principal.addWidget(self.lbl_ActualizarInfo, 0, QtCore.Qt.AlignHCenter)
        self.txt_identidad_cedula = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_identidad_cedula.setStyleSheet("background-color: rgba(0,0,0,75);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 11pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"")
        self.txt_identidad_cedula.setObjectName("txt_identidad_cedula")
        self.lay_ver_principal.addWidget(self.txt_identidad_cedula)
        self.btn_nombre = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_nombre.setStyleSheet("QPushButton {\n"
"    background-color:rgba(176, 142, 99,210);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_nombre.setObjectName("btn_nombre")
        self.lay_ver_principal.addWidget(self.btn_nombre)
        self.btn_id = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_id.setStyleSheet("QPushButton {\n"
"    background-color:rgba(176, 142, 99,210);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_id.setObjectName("btn_id")
        self.lay_ver_principal.addWidget(self.btn_id)
        self.btn_objetivo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_objetivo.setStyleSheet("QPushButton {\n"
"    background-color:rgba(176, 142, 99,210);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_objetivo.setObjectName("btn_objetivo")
        self.lay_ver_principal.addWidget(self.btn_objetivo)
        self.btn_patologias = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_patologias.setStyleSheet("QPushButton {\n"
"    background-color:rgba(176, 142, 99,210);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_patologias.setObjectName("btn_patologias")
        self.lay_ver_principal.addWidget(self.btn_patologias)
        self.btn_inscripcion = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_inscripcion.setStyleSheet("QPushButton {\n"
"    background-color:rgba(176, 142, 99,210);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_inscripcion.setObjectName("btn_inscripcion")
        self.lay_ver_principal.addWidget(self.btn_inscripcion)
        self.btn_foto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_foto.setStyleSheet("QPushButton {\n"
"    background-color:rgba(176, 142, 99,210);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 0, 225);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(170, 85, 0, 225);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_foto.setObjectName("btn_foto")
        self.lay_ver_principal.addWidget(self.btn_foto)

        self.retranslateUi(Cambiar_info_cliente)
        QtCore.QMetaObject.connectSlotsByName(Cambiar_info_cliente)

    def retranslateUi(self, Cambiar_info_cliente):
        _translate = QtCore.QCoreApplication.translate
        Cambiar_info_cliente.setWindowTitle(_translate("Cambiar_info_cliente", "Actualizar información del cliente"))
        self.lbl_ActualizarInfo.setText(_translate("Cambiar_info_cliente", "Actualizar información del cliente"))
        self.txt_identidad_cedula.setPlaceholderText(_translate("Cambiar_info_cliente", "Inserte el No de identidad/cedula del cliente"))
        self.btn_nombre.setText(_translate("Cambiar_info_cliente", "Nombre"))
        self.btn_id.setText(_translate("Cambiar_info_cliente", "No de identidad/cedula"))
        self.btn_objetivo.setText(_translate("Cambiar_info_cliente", "Objetivo"))
        self.btn_patologias.setText(_translate("Cambiar_info_cliente", "Patologias"))
        self.btn_inscripcion.setText(_translate("Cambiar_info_cliente", "Inscripción"))
        self.btn_foto.setText(_translate("Cambiar_info_cliente", "Foto"))
from gimnasio.images import imagenes_rc
