# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cambiar_patologias.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActualizarPatologias(object):
    def setupUi(self, ActualizarPatologias):
        ActualizarPatologias.setObjectName("ActualizarPatologias")
        ActualizarPatologias.resize(299, 159)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/lapiz_editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ActualizarPatologias.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ActualizarPatologias)
        self.gridLayout.setObjectName("gridLayout")
        self.lay_ver_principal = QtWidgets.QVBoxLayout()
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_actualizarPatologias = QtWidgets.QLabel(ActualizarPatologias)
        self.lbl_actualizarPatologias.setStyleSheet("font: 11pt \"Gill Sans MT\";")
        self.lbl_actualizarPatologias.setObjectName("lbl_actualizarPatologias")
        self.lay_ver_principal.addWidget(self.lbl_actualizarPatologias, 0, QtCore.Qt.AlignLeft)
        self.txt_patologias = QtWidgets.QPlainTextEdit(ActualizarPatologias)
        self.txt_patologias.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius: 5px;\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";")
        self.txt_patologias.setObjectName("txt_patologias")
        self.lay_ver_principal.addWidget(self.txt_patologias)
        self.btn_agregar_patologias = QtWidgets.QPushButton(ActualizarPatologias)
        self.btn_agregar_patologias.setObjectName("btn_agregar_patologias")
        self.lay_ver_principal.addWidget(self.btn_agregar_patologias)
        self.gridLayout.addLayout(self.lay_ver_principal, 0, 0, 1, 1)

        self.retranslateUi(ActualizarPatologias)
        QtCore.QMetaObject.connectSlotsByName(ActualizarPatologias)

    def retranslateUi(self, ActualizarPatologias):
        _translate = QtCore.QCoreApplication.translate
        ActualizarPatologias.setWindowTitle(_translate("ActualizarPatologias", "Actualizar Patologias"))
        self.lbl_actualizarPatologias.setText(_translate("ActualizarPatologias", "Actualizar Patologias:"))
        self.txt_patologias.setPlaceholderText(_translate("ActualizarPatologias", "Inserte patologias separadas por una coma \",\"."))
        self.btn_agregar_patologias.setText(_translate("ActualizarPatologias", "Agregar"))
from gimnasio.images import imagenes_rc
