# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entrar_gimnasio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Entrar_gimnasio(object):
    def setupUi(self, Entrar_gimnasio):
        Entrar_gimnasio.setObjectName("Entrar_gimnasio")
        Entrar_gimnasio.resize(568, 441)
        Entrar_gimnasio.setMinimumSize(QtCore.QSize(568, 441))
        Entrar_gimnasio.setMaximumSize(QtCore.QSize(568, 441))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/entrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Entrar_gimnasio.setWindowIcon(icon)
        self.wdg_fondo_principal = QtWidgets.QWidget(Entrar_gimnasio)
        self.wdg_fondo_principal.setGeometry(QtCore.QRect(0, 0, 711, 491))
        self.wdg_fondo_principal.setStyleSheet("QWidget #wdg_fondo_principal {\n"
"    \n"
"    \n"
"    background-image: url(:/imagenes/gimnasio_cambiar_info.jpg);\n"
"background-position: center;\n"
"}")
        self.wdg_fondo_principal.setObjectName("wdg_fondo_principal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wdg_fondo_principal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 417))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_entrar = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_entrar.setStyleSheet("background-color:rgba(212, 212, 0, 177);\n"
"border-radius:5px;\n"
"padding-right:30px;\n"
"padding-left:30px;\n"
"font: 30pt \"Gill Sans MT Condensed\";\n"
"color: rgb(255, 255, 255);\n"
"qproperty-alignment: AlignCenter;")
        self.lbl_entrar.setObjectName("lbl_entrar")
        self.lay_ver_principal.addWidget(self.lbl_entrar)
        self.lay_hor_datos = QtWidgets.QHBoxLayout()
        self.lay_hor_datos.setObjectName("lay_hor_datos")
        self.lay_ver_foto = QtWidgets.QVBoxLayout()
        self.lay_ver_foto.setObjectName("lay_ver_foto")
        self.lcd_hora = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        self.lcd_hora.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.lcd_hora.setObjectName("lcd_hora")
        self.lay_ver_foto.addWidget(self.lcd_hora)
        self.lbl_foto = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_foto.setMinimumSize(QtCore.QSize(217, 178))
        self.lbl_foto.setMaximumSize(QtCore.QSize(217, 178))
        self.lbl_foto.setStyleSheet("background-color: rgba(255,255,255,166);\n"
"border: 2px solid rgba(255,255, 255, 255);\n"
"border-radius:20px;\n"
"padding:10px 20px 10px 20px;")
        self.lbl_foto.setText("")
        self.lbl_foto.setPixmap(QtGui.QPixmap(":/imagenes/persona.png"))
        self.lbl_foto.setScaledContents(True)
        self.lbl_foto.setObjectName("lbl_foto")
        self.lay_ver_foto.addWidget(self.lbl_foto)
        self.lay_hor_datos.addLayout(self.lay_ver_foto)
        self.lay_frm_datos = QtWidgets.QFormLayout()
        self.lay_frm_datos.setVerticalSpacing(40)
        self.lay_frm_datos.setObjectName("lay_frm_datos")
        self.lbl_nombre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_nombre.setStyleSheet("font: 13pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lay_frm_datos.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_nombre)
        self.txt_nombre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_nombre.setMaximumSize(QtCore.QSize(217, 27))
        self.txt_nombre.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(255, 255, 255, 255);\n"
"padding-bottom: 5px;\n"
"font: 12pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);")
        self.txt_nombre.setReadOnly(True)
        self.txt_nombre.setObjectName("txt_nombre")
        self.lay_frm_datos.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_nombre)
        self.lbl_fecha_actual = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_fecha_actual.setStyleSheet("font: 13pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_fecha_actual.setObjectName("lbl_fecha_actual")
        self.lay_frm_datos.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_fecha_actual)
        self.dat_fecha_actual = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dat_fecha_actual.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(255,255, 255, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"qproperty-alignment: AlignCenter;")
        self.dat_fecha_actual.setReadOnly(True)
        self.dat_fecha_actual.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dat_fecha_actual.setObjectName("dat_fecha_actual")
        self.lay_frm_datos.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dat_fecha_actual)
        self.lbl_fecha_final = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_fecha_final.setStyleSheet("font: 13pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_fecha_final.setObjectName("lbl_fecha_final")
        self.lay_frm_datos.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_fecha_final)
        self.dat_fecha_final = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dat_fecha_final.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(255,255, 255, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"qproperty-alignment: AlignCenter;")
        self.dat_fecha_final.setReadOnly(True)
        self.dat_fecha_final.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dat_fecha_final.setObjectName("dat_fecha_final")
        self.lay_frm_datos.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dat_fecha_final)
        self.lbl_permiso = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_permiso.setStyleSheet("font: 13pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.lbl_permiso.setObjectName("lbl_permiso")
        self.lay_frm_datos.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_permiso)
        self.chk_permiso_entrada = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.chk_permiso_entrada.setStyleSheet("font: 11pt \"Gill Sans MT\"; color: rgb(255, 255, 255);")
        self.chk_permiso_entrada.setCheckable(False)
        self.chk_permiso_entrada.setObjectName("chk_permiso_entrada")
        self.lay_frm_datos.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.chk_permiso_entrada)
        self.lay_hor_datos.addLayout(self.lay_frm_datos)
        self.lay_ver_principal.addLayout(self.lay_hor_datos)
        self.txt_cedula_TI = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_cedula_TI.setStyleSheet("background-color: rgba(0,0,0,157);\n"
"border: none;\n"
"padding-bottom: 5px;\n"
"border-radius:5px;\n"
"font: 18pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"qproperty-alignment: AlignCenter;")
        self.txt_cedula_TI.setObjectName("txt_cedula_TI")
        self.lay_ver_principal.addWidget(self.txt_cedula_TI)
        self.lay_ver_principal.setStretch(0, 1)
        self.lay_ver_principal.setStretch(1, 2)
        self.lay_ver_principal.setStretch(2, 1)

        self.retranslateUi(Entrar_gimnasio)
        QtCore.QMetaObject.connectSlotsByName(Entrar_gimnasio)

    def retranslateUi(self, Entrar_gimnasio):
        _translate = QtCore.QCoreApplication.translate
        Entrar_gimnasio.setWindowTitle(_translate("Entrar_gimnasio", "Entrar al gimnasio"))
        self.lbl_entrar.setText(_translate("Entrar_gimnasio", "Entrar"))
        self.lbl_nombre.setText(_translate("Entrar_gimnasio", "Nombre:"))
        self.lbl_fecha_actual.setText(_translate("Entrar_gimnasio", "Fecha actual:"))
        self.lbl_fecha_final.setText(_translate("Entrar_gimnasio", "Fecha final:"))
        self.lbl_permiso.setText(_translate("Entrar_gimnasio", "Permiso: "))
        self.chk_permiso_entrada.setText(_translate("Entrar_gimnasio", "Permiso de entrada"))
        self.txt_cedula_TI.setPlaceholderText(_translate("Entrar_gimnasio", "Inserte su No de identidad/Cedula"))
from gimnasio.images import imagenes_rc
