# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remover_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clientes_remover(object):
    def setupUi(self, Clientes_remover):
        Clientes_remover.setObjectName("Clientes_remover")
        Clientes_remover.resize(370, 192)
        Clientes_remover.setMinimumSize(QtCore.QSize(370, 192))
        Clientes_remover.setMaximumSize(QtCore.QSize(370, 192))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagenes/basura.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Clientes_remover.setWindowIcon(icon)
        self.wdg_principal = QtWidgets.QWidget(Clientes_remover)
        self.wdg_principal.setGeometry(QtCore.QRect(0, 0, 371, 251))
        self.wdg_principal.setStyleSheet("QWidget #wdg_principal {\n"
"    \n"
"    background-image: url(:/imagenes/gimnasio_remover.jpg);\n"
"    background-position:center;\n"
"}")
        self.wdg_principal.setObjectName("wdg_principal")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wdg_principal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lay_ver_principal = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lay_ver_principal.setContentsMargins(0, 0, 0, 0)
        self.lay_ver_principal.setObjectName("lay_ver_principal")
        self.lbl_Remover_cliente = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_Remover_cliente.setStyleSheet("\n"
"border-radius:5px;\n"
"padding-right:30px;\n"
"padding-left:30px;\n"
"font: 30pt \"Gill Sans MT Condensed\";\n"
"color: rgb(255, 255, 255);")
        self.lbl_Remover_cliente.setObjectName("lbl_Remover_cliente")
        self.lay_ver_principal.addWidget(self.lbl_Remover_cliente, 0, QtCore.Qt.AlignHCenter)
        self.txt_codigo_cliente = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txt_codigo_cliente.setStyleSheet("\n"
" background-color: rgba(0,0,0,30);\n"
"    border: none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 255);\n"
"padding-bottom: 5px;\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.txt_codigo_cliente.setObjectName("txt_codigo_cliente")
        self.lay_ver_principal.addWidget(self.txt_codigo_cliente)
        self.btn_remover_cliente = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_remover_cliente.setStyleSheet("QPushButton#btn_remover_cliente {\n"
"    background-color:rgba(195, 145, 19, 186);\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_remover_cliente:hover {\n"
"    background-color: rgba(255, 213, 3 , 182);\n"
"    border-radius:5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}\n"
"\n"
"QPushButton#btn_remover_cliente:pressed {\n"
"    background-color:rgba(200, 133, 0, 200);\n"
"    border-radius: 5px;\n"
"    \n"
"    font: 15pt \"Gill Sans MT Condensed\";\n"
"}")
        self.btn_remover_cliente.setObjectName("btn_remover_cliente")
        self.lay_ver_principal.addWidget(self.btn_remover_cliente)
        self.lay_ver_principal.setStretch(1, 2)
        self.lay_ver_principal.setStretch(2, 4)

        self.retranslateUi(Clientes_remover)
        QtCore.QMetaObject.connectSlotsByName(Clientes_remover)

    def retranslateUi(self, Clientes_remover):
        _translate = QtCore.QCoreApplication.translate
        Clientes_remover.setWindowTitle(_translate("Clientes_remover", "Remover cliente"))
        self.lbl_Remover_cliente.setText(_translate("Clientes_remover", "Remover Cliente"))
        self.txt_codigo_cliente.setPlaceholderText(_translate("Clientes_remover", "Codigo del cliente"))
        self.btn_remover_cliente.setText(_translate("Clientes_remover", "Remover cliente"))
from gimnasio.images import imagenes_rc
